blogapp/urls.py
from django.urls import path
from . import views
from .views import *
import users
from users.views import register

app_name = 'blogapp'

urlpatterns = [
    path('', users.views.register, name='home'),
    path('home/', views.blog_list, name='blogs'),
    path('blog/view/<int:pk>/', views.blog_detail, name='blog_view'),
    path('blog/<user>/new/', views.blog_new, name='blog_new'),
    path('blog/delete/<int:pk>/', views.blog_delete, name='blog_remove'),
    path('blog/list/', BlogListView.as_view(), name='blog_list'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/edit/<int:pk>/', views.blog_edit, name='blog_edit'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('api/', include('blogapp.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('user/', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout')
]

blogapp/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.title

blogapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, TextInput

from .models import Post

class WriteBlog(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

        widgets = {
            'title': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Blog title'
                }),
            'text': forms.Textarea(attrs={
                'class': "form-control",
                'style': 'max-width: 3000px;',
                'placeholder': 'Type blog content here..'
                }),
        }

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username"]

blogapp/views.py
from urllib import request
from django.shortcuts import render
from django.utils import timezone
from .models import Post
from rest_framework import generics
from .serializers import BlogSerializer
from rest_framework.response import Response
from django.shortcuts import render, get_object_or_404
from .forms import WriteBlog
from django.shortcuts import redirect
# from celery.schedules import crontab
# from celery.task import periodic_task
# from .tasks import publish_scheduled_posts


# Create your views here.
class BlogListView(generics.ListAPIView):
    queryset = Post.objects.all()
    serializer_class = BlogSerializer

class BlogCreateView(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = BlogSerializer

class BlogDetailView(generics.RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = BlogSerializer

class BlogUpdateView(generics.RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = BlogSerializer

class BlogDeleteView(generics.DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = BlogSerializer

    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        instance.delete()
        return Response(print("Blog Deleted"))

def blog_list(request):
    User = get_user_model()
    posts = Post.objects.filter(date__lte=timezone.now()).order_by('date')
    return render(request, 'blogapp/blog_list.html', {'posts': posts})

from django.contrib.auth import get_user_model
def blog_new(request, user):
    if request.method == "POST":
        form = WriteBlog(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            User = get_user_model()
            user_qs = User.objects.filter(username=user)
            post.author = user_qs[0]
            post.published_date = timezone.now()
            post.save()
            return redirect('blogapp:blog_view', pk=post.pk)
    else:
        form = WriteBlog()
    return render(request, 'blogapp/blog_edit.html', {'form': form})

def blog_edit(request, pk):
    blog = get_object_or_404(Post, pk=pk)

    if request.method != 'POST':
        form = WriteBlog(instance=blog)

    else:
        form = WriteBlog(instance=blog, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogapp:blogs')


    context = {'post': blog, 'form': form}
    return render(request, 'blogapp/blog_edit.html', context)

def blog_detail(request, pk):
    detail = get_object_or_404(Post, pk=pk)
    return render(request, 'blogapp/blog_detail.html', {'detail': detail})

def blog_delete(request, pk):
    blog = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        blog.delete()
        return redirect('blogapp:blogs')
    return render(request, 'blogapp/blog_delete.html', {'blog':blog.title})


# @periodic_task(run_every=(crontab(hour=x, minute=y)))
# def schedule_publishing():
#     publish_scheduled_posts.delay()

users/views.py
# from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib import messages
# from django.contrib.auth.decorators import login_required
#
from .forms import UserRegForm
# from celery.schedules import crontab
# from celery.task import periodic_task
# from .tasks import publish_scheduled_posts
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
# # Create your views here.
#

def register(request):
    if request.method == "POST":
        form = UserRegForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/home')
    else:
        form = UserRegForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    # return render(request, 'users/profile.html')
    return redirect('blogapp:blogs', user = request.user)

blogapp/templates/blogapp/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>Blog Zone</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .banner {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
        .copyright {
            position: fixed;
            bottom: 0;
            width: 100%;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a href="{% url 'blogapp:blogs' %}" class="navbar-brand">Blog Zone</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            {% if user.username|length == 0 %}
                                <a class="nav-link text-black font-weight-bold" href="#">Welcome!</a>
                            {% else %}
                                <a class="nav-link text-black font-weight-bold" href="#">Welcome {{user.username}}!</a>
                            {% endif %}
                        </li>
                        <li class="nav-item text-black">
                            <a href="{% url 'users:login' %}" class="nav-link text-black font-weight-bold">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <header class="banner">
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class=" col-md-8 col-md-10">
                        <div class="site-heading">
                            <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to Blog Zone</h3>
                            <p class="text-light">Elevate your blogging experience with our seamless app...! &nbsp
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey copyright">
            <p class="m-0 text-dark text-center ">Copyright &copy; Blog Zone</p>
        </footer>
    </body>
</html>

blogapp/templates/blogapp/blog_delete.html
{% extends 'blogapp/inner_base.html' %}
    <style>
        .title {
            text-decoration:underline;
            color:grey;
            margin-bottom: 30px;
        }
        .my-3 {
            margin-bottom: 30px;
        }
        .button {
            background-color:#750000;
            color:white;
        }
        .cancelBtn {
            text-decoration:none;
            color:black
        }
    </style>
{% block content %}
<div class="container" style="text-align:center;">
    <div class="row">
        <div class="col-md-12 mt-3 left">
            <legend class="border-bottom mb-4" style="color:black;">Delete Blog</legend>
            <form method="POST" class="post-form">
                {% csrf_token %}
                <h3 class="title">{{ blog.title }}</h3>
                <p class="my-3">
                Delete this blog? <br>
                You will not be able to undo this action.
                </p>
                <button type="submit" class="save btn button" >Yes</button>
                <button class="btn" style="background-color:#E9EAE0;">
                <a class="cancelBtn" href="{% url 'blogapp:blogs' %}">Cancel</a>
                </button>

            </form>
        </div>
    </div>
</div>

{% endblock content %}

blogapp/templates/blogapp/blog_detail.html
{% extends 'blogapp/inner_base.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-12 card mb-4 mt-3 left top">
      <div class="card-body">
        <h1>{% block title %} {{ detail.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ detail.author }} | {{ detail.date }}</p>
        <p class="card-text ">{{ detail.text | safe }}</p>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

blogapp/templates/blogapp/blog_edit.html
{% extends 'blogapp/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            <legend class="border-bottom mb-4" style="color:black;">Create Blog</legend>
            <form method="POST" class="post-form">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-secondary">Post Now</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

blogapp/templates/blogapp/blog_list.html
{% extends "blogapp/base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mt-3 left">
            {% for post in posts %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title"><a href="{% url 'blogapp:blog_view' pk=post.pk %}">{{ post.title }}</a></h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.date}} </p>
                    <p class="card-text">{{post.text|slice:":200" }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'blogapp/sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{% endblock content %}

blogapp/templates/blogapp/blog_new.html
{% extends 'blogapp/base.html' %}
<style>
    .saveBtn {
        background-color:#3398E1;
        color:white;
    }
</style>
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-3 left">
            <legend class="border-bottom mb-4" style="color:black;">Edit Blog</legend>
            <form action="{% url 'blogs:blog_edit pk=post.pk %}" method="POST" class="post-form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn saveBtn">Post Now</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

blogapp/templates/blogapp/inner_base.html
<!DOCTYPE html>
<html>

    <head>
        <title>Blog Zone</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .banner {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
        .copyright {
            position: fixed;
            bottom: 0;
            width: 100%;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a href="{% url 'blogapp:blogs' %}" class="navbar-brand">Blog Zone </a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            {% if user.username|length == 0 %}
                                <a class="nav-link text-black font-weight-bold" href="#">Welcome!</a>
                            {% else %}
                                <a class="nav-link text-black font-weight-bold" href="#">Welcome {{user.username}}!</a>
                            {% endif %}
                        </li>
                        <li class="nav-item text-black">
                            <a href="{% url 'logout' %}" class="nav-link text-black font-weight-bold" href="#">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <header class="banner">
            <div class="overlay"></div>
            <div class="container">
                <div class="row" style="text-align:center;">
                    <div class=" col-md-12">
                        <div class="site-heading">
                            <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to Blog Zone</h3>
                            <p class="text-light">Elevate your blogging experience with our seamless app...! &nbsp
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey copyright">
            <p class="m-0 text-dark text-center ">Copyright &copy; Blog Zone</p>
        </footer>
    </body>
</html>

blogapp/templates/blogapp/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> This is a blog app built using django framework with user authentication, scheduled postings and seamless user experience.</p>
    </div>
</div>
    <div class="text-center">
        <a href="{% url 'blogapp:blog_new' user.username %}" class="btn btn-success">Write a New Blog</a>
    </div>
    <br>
    <div class="text-center">
        <h3>My Blogs</h3>
    </div>
    <br>
    <div class="col-md-12 mt-3 left">
        {% for post in posts %}
        {% if post.author == request.user %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title"><a href="{% url 'blogapp:blog_view' pk=post.pk %}">{{ post.title }}</a></h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.date}} </p>
                    <p class="card-text">{{post.text|slice:":200" }}</p>
                    <span style="color:blue"><a href="{% url 'blogapp:blog_edit' pk=post.pk %}">Edit Blog</a></span>
                    <span style="color:red;float:right;"><a href="{% url 'blogapp:blog_remove' pk=post.pk %}" style="color:red;">Delete Blog</a></span>
                </div>
            </div>
        {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock sidebar %}

users/templates/users/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>Blog Zone</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a href="{% url 'blogapp:blogs' user %}" class="navbar-brand">Blog Zone</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            {% if user|length == 0 %}
                                <a class="nav-link text-black font-weight-bold" href="#">Welcome!</a>
                            {% else %}
                                <a class="nav-link text-black font-weight-bold" href="#">Welcome {{user}}!</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <header class="masthead">
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class=" col-md-8 col-md-10">
                        <div class="site-heading">
                            <h3 class=" site-heading my-4 text-white"> Welcome to Blog Zone</h3>
                            <p class="text-light">Elevate your blogging experience with our seamless app...! &nbsp
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Copyright &copy; Blog Zone</p>
        </footer>
    </body>
</html>

users/templates/users/logout.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="container" style="margin: 50px">
        <h3>You have been Logged out</h3>
        <h5><a href="{% url 'users:login' %}">Login Again</a></h5>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container" style="margin-top: 30px;">
        {% if user is not None %}
            <legend class="border-bottom mb-4" style="color:black;"><h3>Welcome <b>{{user}}!</b></h3></legend>
        {% else %}
            <legend class="border-bottom mb-4" style="color:black;"><h3>Welcome!</h3></legend>
        {% endif %}
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
        {% block content %}
        <!-- Content Goes here -->
        <div class="container" style="margin-top: 30px;">
            <form action="" method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4" style="color:black;">Start Blogging</legend>
                    {{ form | crispy }}
                </fieldset>
                <div class="form-group" id="signup-button">
                    <button class="btn" style="color: white; background-color:lightseagreen;">Sign Up</button>
                </div>
                <div class="form-group">
                    <small class="text-muted ml-3" >Already have an account? <a href="{% url 'login' %}">Sign In</a></small>
                </div>
            </form>
        </div>
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Copyright &copy; Blog Zone</p>
        </footer>
    </body>
</html>